apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  description: Adds a Go application with AWS resources
  name: app-with-aws-resources
  title: Add a Go App with AWS resources
spec:
  owner: guest
  parameters:
    - dependencies:
        resources:
          oneOf:
            - $yaml: resources/awsblueprints.io.subscriptionfilter.yaml
            - $yaml: resources/awsblueprints.io.eventsourcemapping.yaml
            - $yaml: resources/awsblueprints.io.iampolicy.yaml
            - $yaml: resources/awsblueprints.io.irsa.yaml
            - $yaml: resources/awsblueprints.io.xkinesisfirehose.yaml
            - $yaml: resources/awsblueprints.io.firehoseapp.yaml
            - $yaml: resources/awsblueprints.io.encryptionkey.yaml
            - $yaml: resources/awsblueprints.io.lambdafunction.yaml
            - $yaml: resources/awsblueprints.io.objectstorage.yaml
            - $yaml: resources/awsblueprints.io.serverlessapp.yaml
            - $yaml: resources/awsblueprints.io.notification.yaml
            - $yaml: resources/awsblueprints.io.fanout.yaml
            - $yaml: resources/awsblueprints.io.queue.yaml
      description: Select a AWS resource to add to your repository.
      properties:
        name:
          description: name of this resource. This will be the name of K8s object.
          type: string
        path:
          default: kustomize/base
          description: path to place this file into
          type: string
        resources:
          enum:
            - awsblueprints.io.subscriptionfilter
            - awsblueprints.io.eventsourcemapping
            - awsblueprints.io.iampolicy
            - awsblueprints.io.irsa
            - awsblueprints.io.xkinesisfirehose
            - awsblueprints.io.firehoseapp
            - awsblueprints.io.encryptionkey
            - awsblueprints.io.lambdafunction
            - awsblueprints.io.objectstorage
            - awsblueprints.io.serverlessapp
            - awsblueprints.io.notification
            - awsblueprints.io.fanout
            - awsblueprints.io.queue
          type: string
      required:
        - awsResources
        - name
      title: Choose AWS Resources
    - properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com
            allowedOwners:
              - manabuOrg
      required:
        - repoUrl
      title: Choose your repository location
  steps:
    - action: roadiehq:utils:serialize:yaml
      id: serialize
      input:
        data:
          apiVersion: awsblueprints.io/v1alpha1
          kind: ${{ parameters.awsResources }}
          metadata:
            name: ${{ parameters.name }}
          spec: ${{ parameters.config }}
      name: serialize
    - action: roadiehq:utils:fs:write
      id: write
      input:
        content: ${{ steps['serialize'].output.serialized }}
        path: ${{ parameters.path }}/${{ parameters.name }}.yaml
      name: write-to-file
    - action: publish:github:pull-request
      id: pullRequest
      input:
        branchName: ${{ parameters.name }}-${{ parameters.awsResources}}-${{ user.entity.metadata.name }}
        description: Add ${{ parameters.awsResources}}
        repoUrl: ${{ parameters.repoUrl }}
        sourcePath: ./
        title: Add ${{ parameters.awsResources}}
      name: create-PR
  type: service
